from abc import ABC, abstractmethod

class ComponentFormat(ABC):
    
    def __init__(self, x: int, y: int) -> None:
        self.coords = [x, y]
    
    def selected(self): ...
    def deselected(self): ...
    def refresh(self): ...
    @abstractmethod
    def get_drawinfo(self): ...
    def action(self, **kwargs): ...
    